package org.webstories.release.server;

import java.io.File;

public class ServerTasks {
	private File jbossHome;
	
	private ServerTasks( File jbossHome ) {
		this.jbossHome = jbossHome;
	}
	
	public static ServerTasks create( File jbossHome ) {
		return new ServerTasks( jbossHome );
	}
	
	/**
	 * Check if the artifact generated by the last build process should be deployed in the server
	 */
	public boolean isDeployable() {
		// TODO
		return false;
	}
	
	/**
	 * Deploy the artifact generated by the last build process, stopping or restarting the server
	 * if necessary.
	 */
	public void deploy() {
		// TODO
	}
}
